stages:
  - test
  - deploy

test:
  stage: test
  # image: alpine
  # image: docker:latest
  image:
    name: docker:latest
    entrypoint: [""]
  before_script:
    - apk update
    - apk add --no-cache docker-cli-compose
    - which docker-compose || true
    - find / -iname "docker-compose*" 2>/dev/null
    - echo "HOME=$HOME"
    - docker info --format '{{json .ClientInfo.Plugins}}' 2>/dev/null || docker version
    - uname -m
    - docker version --format '{{.Server.Arch}}'
    - docker info --format '{{.OSType}}/{{.Architecture}}'
    - file /usr/local/libexec/docker/cli-plugins/docker-compose
  script:
    - echo "HELLO CI"
    - echo "BRANCH=$CI_COMMIT_BRANCH"
    - echo "REF=$CI_COMMIT_REF_NAME"
    - echo "PIPELINE_SOURCE=$CI_PIPELINE_SOURCE"
    - docker compose build
    - docker compose up -d
    - docker compose ps

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "===DEPLOY START==="