stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main

  image: docker:latest

  services:
    - docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - sleep 120
    - echo "===TEST START==="
    - echo "$CAPTCHA_KEY" > captcha.json
    - echo "$SERVER_KEY" > server.key
    - echo "$SERVER_CRT" > server.crt
    - docker compose down
    - docker compose build
    - docker compose up -d
    - echo "===TEST END==="